### ISSUE TITLE
How to convert image to base64

### ISSUE THREAD

**Issue by hellof20** [google/visualblocks#38]
Hi, I want to send images to other API services for processing, such as the image service of Vertex AI, to get the description of the image. Since the API service [can only accept strings in base64 format](https://cloud.google.com/vertex-ai/docs/generative-ai/image/image-captioning#get-captions), but I don't know how to convert images to bas64 in Virtual blocks, need your help.

**Comment by ruofeidu** [comment]
Thanks hellof20 for the request - we have it implemented already and it's just not published yet. I think there should be no blocker to have that: @jinjingforever  to update :)

**Comment by gbaned** [comment]
Hi @hellof20 The node image to base64 has been published and it is available in visual blocks nodes library. Please find the below screenshot for reference. Can you please check? Thank you!

![image](https://github.com/google/visualblocks/assets/48215717/10ab1833-8f83-4ca7-a46d-9b8e164819b7)
