### ISSUE TITLE
Import models from Teachable Machines -> Tensorflow

### ISSUE THREAD

**Issue by xavido** [google/visualblocks#52]
Hi,
 Is there any way to import models from Teachable Machine ? 
 Thanks!

Xavi

**Comment by mattsoulanille** [comment]
Yes, but it depends on the model type. For example, [here's a pipeline I made that predicts whether a cellphone is in the user's hand](https://github.com/user-attachments/files/15890339/teachable_machine_image.json). It uses the teachable machine 224x224px model (based on MobileNet). To host the model, I exported it as Tensorflow.js in teachable machine and uploaded it as a sharable link. When you export your model, you'll need to append `/model.json` to the link to run it in VisualBlocks.

Different model / project types might not have their pre and post processing pipelines supported at the moment.

**Comment by ruofeidu** [comment]
Thank you Matthew for the great example!!! Feel free to make a pull request to https://github.com/google/visualblocks/tree/main/pipelines
and I'm happy to highlight your example on Community Page!

**Comment by ruofeidu** [comment]
Thank you Matthew for the great example!!! Feel free to make a pull request
to https://github.com/google/visualblocks/tree/main/pipelines
and I'm happy to highlight your example on Community Page!!

**Comment by xavido** [comment]
Wow, thanks so much Mathew ! I will test it. Thanks so much! I'm using this workflow to work with primary and secondary teachers in rapid prototyping educational projects.

**Comment by xavido** [comment]
I close the issue as it's fixed.
